---
title: "Probability"
---
  
```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
library(cmapR)
library(colorspace)
library(scales)
library(mccf1)
library(ROCR)
library(mccr)
```


```{r demo_curves, echo=F,message=F,warning=F,fig.height=9,fig.width=9,fig.show='hold'}
DEMOCURVES <- function(LIG,CT) {
  
  layout(matrix(c(1:4,5,5,6,6,rep(7,4),rep(8,4)),8))
  
  par(mar=c(2,3,0.5,1),mgp=2:0)
  hist(scores_all[[LIG]][[CT]]$score[!scores_all[[LIG]][[CT]]$label & 
                                       !scores_all[[LIG]][[CT]]$train],
       xlim=0:1,xlab=NA,ylab="All.False",main=NA,col="red")
  abline(v=0.5,lty=2)
  hist(scores_new[[LIG]][[CT]]$score[!scores_new[[LIG]][[CT]]$label & 
                                       !scores_new[[LIG]][[CT]]$train],
       xlim=0:1,xlab=NA,ylab="Withheld.False",main=NA,col="dodgerblue")
  abline(v=0.5,lty=2)
  hist(scores_all[[LIG]][[CT]]$score[scores_all[[LIG]][[CT]]$label & 
                                       !scores_all[[LIG]][[CT]]$train],
       xlim=0:1,xlab=NA,ylab="All.True",main=NA,col="red")
  abline(v=0.5,lty=2)
  hist(scores_new[[LIG]][[CT]]$score[scores_all[[LIG]][[CT]]$label & 
                                       !scores_all[[LIG]][[CT]]$train],
       xlim=0:1,xlab=NA,ylab="Withheld.True",main=NA,col="dodgerblue")
  abline(v=0.5,lty=2)
  
  
  temp_all <- prediction(scores_all[[LIG]][[CT]]$score[!scores_all[[LIG]][[CT]]$train],
                         as.integer(scores_all[[LIG]][[CT]]$label[!scores_all[[LIG]][[CT]]$train]))
  temp_all_f1 <- performance(temp_all,"f")
  temp_new <- prediction(scores_new[[LIG]][[CT]]$score[!scores_new[[LIG]][[CT]]$train],
                         as.integer(scores_new[[LIG]][[CT]]$label[!scores_new[[LIG]][[CT]]$train]))
  temp_new_pr <- performance(temp_new,"prec","rec")
  temp_new_f1 <- performance(temp_new,"f")
  
  plot(temp_all_f1@x.values[[1]],temp_all_f1@y.values[[1]],
       bty="n",type="l",col="red",ylab="F1",
       xlim=0:1,ylim=c(0,max(c(temp_all_f1@y.values[[1]],temp_new_f1@y.values[[1]]),na.rm=T)))
  points(temp_new_f1@x.values[[1]],temp_new_f1@y.values[[1]],type="l",col="dodgerblue")
  abline(v=0.5,lty=2)
  
  
  temp_seq <- seq(min(scores_all[[LIG]][[CT]]$label[!scores_all[[LIG]][[CT]]$train]),
                  max(scores_all[[LIG]][[CT]]$label[!scores_all[[LIG]][[CT]]$train]),
                  length.out=500)
  temp_all_mcc <- sapply(temp_seq,function(X)
    mccr(as.integer(scores_all[[LIG]][[CT]]$label[!scores_all[[LIG]][[CT]]$train]),
         as.integer(scores_all[[LIG]][[CT]]$score[!scores_all[[LIG]][[CT]]$train] >= X)))
  temp_new_mcc <- sapply(temp_seq,function(X)
    mccr(as.integer(scores_new[[LIG]][[CT]]$label[!scores_new[[LIG]][[CT]]$train]),
         as.integer(scores_new[[LIG]][[CT]]$score[!scores_new[[LIG]][[CT]]$train] >= X)))
  plot(temp_seq,temp_all_mcc,ylab="MCC",
       bty="n",type="l",col="red",
       xlim=0:1,ylim=range(c(temp_all_mcc,temp_new_mcc)))
  points(temp_seq,temp_new_mcc,type="l",col="dodgerblue")
  abline(v=0.5,lty=2)
  
  
  par(mar=c(3,5,2,1),mgp=2:0,las=1)
  # boxplot(rev(list(All.F=scores_all[[LIG]][[CT]]$score[!scores_all[[LIG]][[CT]]$label & 
  #                                                        !scores_all[[LIG]][[CT]]$train],
  #                  Withheld.F=scores_new[[LIG]][[CT]]$score[!scores_new[[LIG]][[CT]]$label & 
  #                                                             !scores_new[[LIG]][[CT]]$train],
  #                  All.T=scores_all[[LIG]][[CT]]$score[scores_all[[LIG]][[CT]]$label & 
  #                                                        !scores_all[[LIG]][[CT]]$train],
  #                  Withheld.T=scores_new[[LIG]][[CT]]$score[scores_new[[LIG]][[CT]]$label & 
  #                                                             !scores_new[[LIG]][[CT]]$train])),
  #         horizontal=T,ylim=0:1,col=alpha(c("dodgerblue","red","dodgerblue","red"),0.8),
  #         xlab="Random forest model probability",main=paste(LIG,"tested on",CT))
  # abline(v=0.5,lty=2,lwd=2)
  
  
  temp_all <- prediction(scores_all[[LIG]][[CT]]$score[!scores_all[[LIG]][[CT]]$train],
                         as.integer(scores_all[[LIG]][[CT]]$label[!scores_all[[LIG]][[CT]]$train]))
  temp_all_pr <- performance(temp_all,"prec","rec")
  temp_all_f1 <- performance(temp_all,"f")
  temp_all_f1 <- temp_all_f1@y.values[[1]][which.min(abs(0.5 - temp_all_f1@x.values[[1]]))]
  temp_all_mcc <- mccr(as.integer(scores_all[[LIG]][[CT]]$label[!scores_all[[LIG]][[CT]]$train]),
                       round(scores_all[[LIG]][[CT]]$score[!scores_all[[LIG]][[CT]]$train]))
  temp_new <- prediction(scores_new[[LIG]][[CT]]$score[!scores_new[[LIG]][[CT]]$train],
                         as.integer(scores_new[[LIG]][[CT]]$label[!scores_new[[LIG]][[CT]]$train]))
  temp_new_pr <- performance(temp_new,"prec","rec")
  temp_new_f1 <- performance(temp_new,"f")
  temp_new_f1 <- temp_new_f1@y.values[[1]][which.min(abs(0.5 - temp_new_f1@x.values[[1]]))]
  temp_new_mcc <- mccr(as.integer(scores_new[[LIG]][[CT]]$label[!scores_new[[LIG]][[CT]]$train]),
                       round(scores_new[[LIG]][[CT]]$score[!scores_new[[LIG]][[CT]]$train]))
  
  par(mar=c(3,3,2,1),mgp=2:0)
  plot(temp_all_pr@x.values[[1]],temp_all_pr@y.values[[1]],
       type="l",xlim=0:1,ylim=0:1,col="red",
       xlab=temp_all_pr@x.name,ylab=temp_all_pr@y.name)
  points(temp_all_pr@x.values[[1]][which.min(abs(0.5 - temp_all_pr@alpha.values[[1]]))],
         temp_all_pr@y.values[[1]][which.min(abs(0.5 - temp_all_pr@alpha.values[[1]]))],
         pch=20,col="red4")
  points(temp_new_pr@x.values[[1]],temp_new_pr@y.values[[1]],
         type="l",col="dodgerblue")
  points(temp_new_pr@x.values[[1]][which.min(abs(0.5 - temp_new_pr@alpha.values[[1]]))],
         temp_new_pr@y.values[[1]][which.min(abs(0.5 - temp_new_pr@alpha.values[[1]]))],
         pch=20,col="dodgerblue4")
  legend("topright",bty="n",lty=c(1,NA,NA,1,NA,NA),pch=c(20,NA,NA,20,NA,NA),
         col=c("red",NA,NA,"dodgerblue",NA,NA),
         text.col=c("red","red","red","dodgerblue","dodgerblue","dodgerblue"),
         legend=c("Trained on all (@ 0.5)",
                  paste("F1 @ 0.5:",round(temp_all_f1,2)),
                  paste("MCC @ 0.5:",round(temp_all_mcc,2)),
                  "Withheld cell line (@ 0.5)",
                  paste("F1 @ 0.5:",round(temp_new_f1,2)),
                  paste("MCC @ 0.5:",round(temp_new_mcc,2))))
  mtext(paste(LIG,"tested on",CT),side=3,cex=1.5,font=2,at=-0.1,xpd=NA)
  
  temp_all <- mccf1(as.integer(scores_all[[LIG]][[CT]]$label[!scores_all[[LIG]][[CT]]$train]),
                    scores_all[[LIG]][[CT]]$score[!scores_all[[LIG]][[CT]]$train])
  temp_new <- mccf1(as.integer(scores_new[[LIG]][[CT]]$label[!scores_new[[LIG]][[CT]]$train]),
                    scores_new[[LIG]][[CT]]$score[!scores_new[[LIG]][[CT]]$train])
  
  par(mar=c(3,3,2,1),mgp=2:0)
  plot(temp_all$f1,temp_all$normalized_mcc,
       type="l",xlim=0:1,ylim=0:1,col="red",
       xlab="F1 score",ylab="Normalized MCC")
  points(temp_all$f1[which.min(abs(0.5 - temp_all$thresholds))],
         temp_all$normalized_mcc[which.min(abs(0.5 - temp_all$thresholds))],
         pch=20,col="red4")
  points(temp_new$f1,temp_new$normalized_mcc,type="l",col="dodgerblue")
  points(temp_new$f1[which.min(abs(0.5 - temp_new$thresholds))],
         temp_new$normalized_mcc[which.min(abs(0.5 - temp_new$thresholds))],
         pch=20,col="dodgerblue4")
  legend("bottomright",bty="n",lty=c(1,NA,1,NA),pch=c(20,NA,20,NA),
         col=c("red",NA,"dodgerblue",NA),text.col=c("red","red","dodgerblue","dodgerblue"),
         legend=c("Trained on all (@ 0.5)",
                  paste("MCC/F1 metric:",round(mccf1_all[CT,LIG],2)),
                  "Withheld cell line (@ 0.5)",
                  paste("MCC/F1 metric:",round(mccf1_new[CT,LIG],2))))
}
```


## Breast lines only, level 5 data

```{r lvl5_breast_load, echo=F,message=F,warning=F}
temp_load1 <- load("~/Dropbox/GDB_archive/CMapCorr_files/200817_lvl5_breastonly.RData")
temp_load2 <- load("~/Dropbox/GDB_archive/CMapCorr_files/200817_newVall_probs_breast_lvl5.RData")

```

```{r lvl5_breast_heatmap, echo=F,message=F,warning=F,fig.height=9,fig.width=7,fig.show='hold'}
temp_both <- do.call(rbind,lapply(rownames(mccf1_all),function(X) { 
  temp <- rbind(mccf1_new[X,],mccf1_all[X,]) 
  rownames(temp) <- c(X,paste0(X,"_ctrl"))
  return(temp)
}))

par(mar=c(1,5,7,1),mgp=2:0,las=2)
image(z=temp_both[,seq(ncol(temp_both),1)],
      x=1:nrow(temp_both),y=1:ncol(temp_both),
      col=sequential_hcl(100,palette="inferno",rev=T), #breaks=0:100,
      xaxt="n",yaxt="n",xlab=NA,ylab=NA)
mtext(rownames(temp_both),side=3,at=1:nrow(temp_both),adj=0,line=0.1)
mtext("Withheld cell line",side=3,line=5.5,cex=1.5,font=2,las=0)
mtext(rev(colnames(temp_both)),
      side=2,at=1:ncol(temp_both),adj=1,line=0.1)
mtext("Ligand",side=2,line=3.5,cex=1.5,font=2,las=0)
mtext("MCC/F1 metric %",side=1,line=0,at=nrow(temp_both) + 0.5,adj=1,las=0,col="dodgerblue")
text(as.vector(sapply(1:ncol(temp_both),function(X) 1:nrow(temp_both))),
     as.vector(sapply(ncol(temp_both):1,function(X) rep(X,nrow(temp_both)))),
     labels=as.vector(round(temp_both * 100)),cex=0.8,col="dodgerblue")

```

```{r lvl5_breast_MA, echo=F,message=F,warning=F,fig.height=8,fig.width=9,fig.show='hold'}
temp_lig <- factor(sapply(colnames(mccf1_all),function(X) rep(X,nrow(mccf1_all))),levels=lig29)
temp_ct <- factor(sapply(colnames(mccf1_all),function(X) rownames(mccf1_all)),levels=ctBR)

par(mfrow=c(2,2),mar=c(3,3,2,1),mgp=2:0)
plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Coloured by ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Coloured by cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Average per ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(mccf1_new),temp_lig,mean) - 
  tapply(as.vector(mccf1_all),temp_lig,mean)
temp_y <- colMeans(rbind(tapply(as.vector(mccf1_new),temp_lig,mean),
                         tapply(as.vector(mccf1_all),temp_lig,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_lig)),palette="dark3"))
temp_ythresh <- 0.3
text(temp_x[temp_y > temp_ythresh],temp_y[temp_y > temp_ythresh],
     labels=names(temp_y)[temp_y > temp_ythresh],pos=4,
     col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_y > temp_ythresh])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Average per cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(mccf1_new),temp_ct,mean) - 
  tapply(as.vector(mccf1_all),temp_ct,mean)
temp_y <- colMeans(rbind(tapply(as.vector(mccf1_new),temp_ct,mean),
                         tapply(as.vector(mccf1_all),temp_ct,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))
temp_ythresh <- 0.25
legend("topleft",bty="n",levels(temp_ct),pch=19,cex=0.9,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"),
       text.col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))

```

```{r lvl5_breast_inspect, echo=F,message=F,warning=F,fig.height=9,fig.width=9,fig.show='hold'}
DEMOCURVES("TNF","MDAMB231")
DEMOCURVES("TNF","MCF10A")

```

```{r lvl5_breast_MA_MCC, echo=F,message=F,warning=F,fig.height=8,fig.width=9,fig.show='hold'}
temp_mcc_all <- sapply(names(scores_all),function(LIG) {
  sapply(names(scores_all[[LIG]]),function(CT) {
    mccr(as.integer(scores_all[[LIG]][[CT]]$label[!scores_all[[LIG]][[CT]]$train]),
         as.integer(scores_all[[LIG]][[CT]]$score[!scores_all[[LIG]][[CT]]$train] >= .5))
  })
})
temp_mcc_new <- sapply(names(scores_new),function(LIG) {
  sapply(names(scores_new[[LIG]]),function(CT) {
    mccr(as.integer(scores_new[[LIG]][[CT]]$label[!scores_new[[LIG]][[CT]]$train]),
         as.integer(scores_new[[LIG]][[CT]]$score[!scores_new[[LIG]][[CT]]$train] >= .5))
  })
})

temp_lig <- factor(sapply(colnames(temp_mcc_all),function(X) rep(X,nrow(temp_mcc_all))),levels=lig29)
temp_ct <- factor(sapply(colnames(temp_mcc_all),function(X) rownames(temp_mcc_all)),levels=ctBR)

par(mfrow=c(2,2),mar=c(3,3,2,1),mgp=2:0)
plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Coloured by ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Coloured by cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Average per ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(temp_mcc_new),temp_lig,mean) - 
  tapply(as.vector(temp_mcc_all),temp_lig,mean)
temp_y <- colMeans(rbind(tapply(as.vector(temp_mcc_new),temp_lig,mean),
                         tapply(as.vector(temp_mcc_all),temp_lig,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_lig)),palette="dark3"))
temp_ythresh <- 0.15
text(temp_x[temp_y > temp_ythresh],temp_y[temp_y > temp_ythresh],
     labels=names(temp_y)[temp_y > temp_ythresh],pos=4,
     col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_y > temp_ythresh])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Average per cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(temp_mcc_new),temp_ct,mean) - 
  tapply(as.vector(temp_mcc_all),temp_ct,mean)
temp_y <- colMeans(rbind(tapply(as.vector(temp_mcc_new),temp_ct,mean),
                         tapply(as.vector(temp_mcc_all),temp_ct,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))
temp_ythresh <- 0.25
legend("topleft",bty="n",levels(temp_ct),pch=19,cex=0.9,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"),
       text.col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))

```

```{r lvl5_breast_cleanup, echo=F,message=F,warning=F}
rm(list=c(temp_load1,temp_load2,grep("^temp",ls(),value=T)))
```

----

## Breast lines only, level 4 data

```{r lvl4_breast_load, echo=F,message=F,warning=F}
temp_load1 <- load("~/Dropbox/GDB_archive/CMapCorr_files/200731_lvl4_breastonly.RData")
temp_load2 <- load("~/Dropbox/GDB_archive/CMapCorr_files/200813_newVall_probs_breast_lvl4.RData")

```


```{r lvl4_breast_heatmap, echo=F,message=F,warning=F,fig.height=9,fig.width=7,fig.show='hold'}
temp_both <- do.call(rbind,lapply(rownames(mccf1_all),function(X) { 
  temp <- rbind(mccf1_new[X,],mccf1_all[X,]) 
  rownames(temp) <- c(X,paste0(X,"_ctrl"))
  return(temp)
}))

par(mar=c(1,5,7,1),mgp=2:0,las=2)
image(z=temp_both[,seq(ncol(temp_both),1)],
      x=1:nrow(temp_both),y=1:ncol(temp_both),
      col=sequential_hcl(100,palette="inferno",rev=T), #breaks=0:100,
      xaxt="n",yaxt="n",xlab=NA,ylab=NA)
mtext(rownames(temp_both),side=3,at=1:nrow(temp_both),adj=0,line=0.1)
mtext("Withheld cell line",side=3,line=5.5,cex=1.5,font=2,las=0)
mtext(rev(colnames(temp_both)),
      side=2,at=1:ncol(temp_both),adj=1,line=0.1)
mtext("Ligand",side=2,line=3.5,cex=1.5,font=2,las=0)
mtext("MCC/F1 metric %",side=1,line=0,at=nrow(temp_both) + 0.5,adj=1,las=0,col="dodgerblue")
text(as.vector(sapply(1:ncol(temp_both),function(X) 1:nrow(temp_both))),
     as.vector(sapply(ncol(temp_both):1,function(X) rep(X,nrow(temp_both)))),
     labels=as.vector(round(temp_both * 100)),cex=0.8,col="dodgerblue")

```

```{r lvl4_breast_MA, echo=F,message=F,warning=F,fig.height=8,fig.width=9,fig.show='hold'}
temp_lig <- factor(sapply(colnames(mccf1_all),function(X) rep(X,nrow(mccf1_all))),levels=lig29)
temp_ct <- factor(sapply(colnames(mccf1_all),function(X) rownames(mccf1_all)),levels=ctBR)

par(mfrow=c(2,2),mar=c(3,3,2,1),mgp=2:0)
plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Coloured by ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Coloured by cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Average per ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(mccf1_new),temp_lig,mean) - 
  tapply(as.vector(mccf1_all),temp_lig,mean)
temp_y <- colMeans(rbind(tapply(as.vector(mccf1_new),temp_lig,mean),
                         tapply(as.vector(mccf1_all),temp_lig,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_lig)),palette="dark3"))
temp_ythresh <- 0.25
text(temp_x[temp_y > temp_ythresh],temp_y[temp_y > temp_ythresh],
     labels=names(temp_y)[temp_y > temp_ythresh],pos=4,
     col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_y > temp_ythresh])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Average per cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(mccf1_new),temp_ct,mean) - 
  tapply(as.vector(mccf1_all),temp_ct,mean)
temp_y <- colMeans(rbind(tapply(as.vector(mccf1_new),temp_ct,mean),
                         tapply(as.vector(mccf1_all),temp_ct,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))
temp_ythresh <- 0.25
legend("topleft",bty="n",levels(temp_ct),pch=19,cex=0.9,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"),
       text.col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))

```

```{r lvl4_breast_MA_MCC, echo=F,message=F,warning=F,fig.height=8,fig.width=9,fig.show='hold'}
temp_mcc_all <- sapply(names(scores_all),function(LIG) {
  sapply(names(scores_all[[LIG]]),function(CT) {
    mccr(as.integer(scores_all[[LIG]][[CT]]$label[!scores_all[[LIG]][[CT]]$train]),
         as.integer(scores_all[[LIG]][[CT]]$score[!scores_all[[LIG]][[CT]]$train] >= .5))
  })
})
temp_mcc_new <- sapply(names(scores_new),function(LIG) {
  sapply(names(scores_new[[LIG]]),function(CT) {
    mccr(as.integer(scores_new[[LIG]][[CT]]$label[!scores_new[[LIG]][[CT]]$train]),
         as.integer(scores_new[[LIG]][[CT]]$score[!scores_new[[LIG]][[CT]]$train] >= .5))
  })
})

temp_lig <- factor(sapply(colnames(temp_mcc_all),function(X) rep(X,nrow(temp_mcc_all))),levels=lig29)
temp_ct <- factor(sapply(colnames(temp_mcc_all),function(X) rownames(temp_mcc_all)),levels=ctBR)

par(mfrow=c(2,2),mar=c(3,3,2,1),mgp=2:0)
plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Coloured by ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Coloured by cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Average per ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(temp_mcc_new),temp_lig,mean) - 
  tapply(as.vector(temp_mcc_all),temp_lig,mean)
temp_y <- colMeans(rbind(tapply(as.vector(temp_mcc_new),temp_lig,mean),
                         tapply(as.vector(temp_mcc_all),temp_lig,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_lig)),palette="dark3"))
temp_ythresh <- 0.15
text(temp_x[temp_y > temp_ythresh],temp_y[temp_y > temp_ythresh],
     labels=names(temp_y)[temp_y > temp_ythresh],pos=4,
     col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_y > temp_ythresh])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Average per cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(temp_mcc_new),temp_ct,mean) - 
  tapply(as.vector(temp_mcc_all),temp_ct,mean)
temp_y <- colMeans(rbind(tapply(as.vector(temp_mcc_new),temp_ct,mean),
                         tapply(as.vector(temp_mcc_all),temp_ct,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))
temp_ythresh <- 0.25
legend("topleft",bty="n",levels(temp_ct),pch=19,cex=0.9,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"),
       text.col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))

```

```{r lvl4_breast_cleanup, echo=F,message=F,warning=F}
rm(list=c(temp_load1,temp_load2,grep("^temp",ls(),value=T)))
```



----

## Breast lines only, level 3 data

```{r lvl3_breast_load, echo=F,message=F,warning=F}
temp_load1 <- load("~/Dropbox/GDB_archive/CMapCorr_files/200730_lvl3_breastonly.RData")
temp_load2 <- load("~/Dropbox/GDB_archive/CMapCorr_files/200813_newVall_probs_breast_lvl3.RData")

```


```{r lvl3_breast_heatmap, echo=F,message=F,warning=F,fig.height=9,fig.width=7,fig.show='hold'}
temp_both <- do.call(rbind,lapply(rownames(mccf1_all),function(X) { 
  temp <- rbind(mccf1_new[X,],mccf1_all[X,]) 
  rownames(temp) <- c(X,paste0(X,"_ctrl"))
  return(temp)
}))

par(mar=c(1,5,7,1),mgp=2:0,las=2)
image(z=temp_both[,seq(ncol(temp_both),1)],
      x=1:nrow(temp_both),y=1:ncol(temp_both),
      col=sequential_hcl(100,palette="inferno",rev=T), #breaks=0:100,
      xaxt="n",yaxt="n",xlab=NA,ylab=NA)
mtext(rownames(temp_both),side=3,at=1:nrow(temp_both),adj=0,line=0.1)
mtext("Withheld cell line",side=3,line=5.5,cex=1.5,font=2,las=0)
mtext(rev(colnames(temp_both)),
      side=2,at=1:ncol(temp_both),adj=1,line=0.1)
mtext("Ligand",side=2,line=3.5,cex=1.5,font=2,las=0)
mtext("MCC/F1 metric %",side=1,line=0,at=nrow(temp_both) + 0.5,adj=1,las=0,col="dodgerblue")
text(as.vector(sapply(1:ncol(temp_both),function(X) 1:nrow(temp_both))),
     as.vector(sapply(ncol(temp_both):1,function(X) rep(X,nrow(temp_both)))),
     labels=as.vector(round(temp_both * 100)),cex=0.8,col="dodgerblue")

```

```{r lvl3_breast_MA, echo=F,message=F,warning=F,fig.height=8,fig.width=9,fig.show='hold'}
temp_lig <- factor(sapply(colnames(mccf1_all),function(X) rep(X,nrow(mccf1_all))),levels=lig29)
temp_ct <- factor(sapply(colnames(mccf1_all),function(X) rownames(mccf1_all)),levels=ctBR)

par(mfrow=c(2,2),mar=c(3,3,2,1),mgp=2:0)
plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Coloured by ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Coloured by cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Average per ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(mccf1_new),temp_lig,mean) - 
  tapply(as.vector(mccf1_all),temp_lig,mean)
temp_y <- colMeans(rbind(tapply(as.vector(mccf1_new),temp_lig,mean),
                         tapply(as.vector(mccf1_all),temp_lig,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_lig)),palette="dark3"))
temp_ythresh <- 0.25
text(temp_x[temp_y > temp_ythresh],temp_y[temp_y > temp_ythresh],
     labels=names(temp_y)[temp_y > temp_ythresh],pos=4,
     col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_y > temp_ythresh])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Average per cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(mccf1_new),temp_ct,mean) - 
  tapply(as.vector(mccf1_all),temp_ct,mean)
temp_y <- colMeans(rbind(tapply(as.vector(mccf1_new),temp_ct,mean),
                         tapply(as.vector(mccf1_all),temp_ct,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))
temp_ythresh <- 0.25
legend("topleft",bty="n",levels(temp_ct),pch=19,cex=0.9,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"),
       text.col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))

```

```{r lvl3_breast_inspect, echo=F,message=F,warning=F,fig.height=9,fig.width=9,fig.show='hold'}
DEMOCURVES("IFNG","MCF10A")

```

```{r lvl3_breast_MA_MCC, echo=F,message=F,warning=F,fig.height=8,fig.width=9,fig.show='hold'}
temp_mcc_all <- sapply(names(scores_all),function(LIG) {
  sapply(names(scores_all[[LIG]]),function(CT) {
    mccr(as.integer(scores_all[[LIG]][[CT]]$label[!scores_all[[LIG]][[CT]]$train]),
         as.integer(scores_all[[LIG]][[CT]]$score[!scores_all[[LIG]][[CT]]$train] >= .5))
  })
})
temp_mcc_new <- sapply(names(scores_new),function(LIG) {
  sapply(names(scores_new[[LIG]]),function(CT) {
    mccr(as.integer(scores_new[[LIG]][[CT]]$label[!scores_new[[LIG]][[CT]]$train]),
         as.integer(scores_new[[LIG]][[CT]]$score[!scores_new[[LIG]][[CT]]$train] >= .5))
  })
})

temp_lig <- factor(sapply(colnames(temp_mcc_all),function(X) rep(X,nrow(temp_mcc_all))),levels=lig29)
temp_ct <- factor(sapply(colnames(temp_mcc_all),function(X) rownames(temp_mcc_all)),levels=ctBR)

par(mfrow=c(2,2),mar=c(3,3,2,1),mgp=2:0)
plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Coloured by ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Coloured by cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Average per ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(temp_mcc_new),temp_lig,mean) - 
  tapply(as.vector(temp_mcc_all),temp_lig,mean)
temp_y <- colMeans(rbind(tapply(as.vector(temp_mcc_new),temp_lig,mean),
                         tapply(as.vector(temp_mcc_all),temp_lig,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_lig)),palette="dark3"))
temp_ythresh <- 0.1
text(temp_x[temp_y > temp_ythresh],temp_y[temp_y > temp_ythresh],
     labels=names(temp_y)[temp_y > temp_ythresh],pos=4,
     col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_y > temp_ythresh])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Average per cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(temp_mcc_new),temp_ct,mean) - 
  tapply(as.vector(temp_mcc_all),temp_ct,mean)
temp_y <- colMeans(rbind(tapply(as.vector(temp_mcc_new),temp_ct,mean),
                         tapply(as.vector(temp_mcc_all),temp_ct,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))
temp_ythresh <- 0.25
legend("topleft",bty="n",levels(temp_ct),pch=19,cex=0.9,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"),
       text.col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))

```

```{r lvl3_breast_cleanup, echo=F,message=F,warning=F}
rm(list=c(temp_load1,temp_load2,grep("^temp",ls(),value=T)))
```


----

## All cell lines, level 5 data

```{r lvl5_load, echo=F,message=F,warning=F}
temp_load1 <- load("~/Dropbox/GDB_archive/CMapCorr_files/lvl5_inputs.RData")
temp_load2 <- load("~/Dropbox/GDB_archive/CMapCorr_files/200817_newVall_probs_lvl5.RData")

```


```{r lvl5_heatmap, echo=F,message=F,warning=F,fig.height=7,fig.width=9,fig.show='hold'}
temp_both <- do.call(rbind,lapply(rownames(mccf1_all),function(X) { 
  temp <- rbind(mccf1_new[X,],mccf1_all[X,]) 
  rownames(temp) <- c(X,paste0(X,"_ctrl"))
  return(temp)
}))

par(mar=c(1,5,7,1),mgp=2:0,las=2)
image(z=temp_both[,seq(ncol(temp_both),1)],
      x=1:nrow(temp_both),y=1:ncol(temp_both),
      col=sequential_hcl(100,palette="inferno",rev=T), #breaks=0:100,
      xaxt="n",yaxt="n",xlab=NA,ylab=NA)
mtext(rownames(temp_both),side=3,at=1:nrow(temp_both),adj=0,line=0.1)
mtext("Withheld cell line",side=3,line=5.5,cex=1.5,font=2,las=0)
mtext(rev(colnames(temp_both)),
      side=2,at=1:ncol(temp_both),adj=1,line=0.1)
mtext("Ligand",side=2,line=3.5,cex=1.5,font=2,las=0)
mtext("MCC/F1 metric %",side=1,line=0,at=nrow(temp_both) + 0.5,adj=1,las=0,col="dodgerblue")
text(as.vector(sapply(1:ncol(temp_both),function(X) 1:nrow(temp_both))),
     as.vector(sapply(ncol(temp_both):1,function(X) rep(X,nrow(temp_both)))),
     labels=as.vector(round(temp_both * 100)),cex=0.8,col="dodgerblue")

```

```{r lvl5_MA, echo=F,message=F,warning=F,fig.height=8,fig.width=9,fig.show='hold'}
temp_lig <- factor(sapply(colnames(mccf1_all),function(X) rep(X,nrow(mccf1_all))),levels=lig16)
temp_ct <- factor(sapply(colnames(mccf1_all),function(X) rownames(mccf1_all)),levels=ct14)

par(mfrow=c(2,2),mar=c(3,3,2,1),mgp=2:0)
plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Coloured by ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Coloured by cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Average per ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(mccf1_new),temp_lig,mean) - 
  tapply(as.vector(mccf1_all),temp_lig,mean)
temp_y <- colMeans(rbind(tapply(as.vector(mccf1_new),temp_lig,mean),
                         tapply(as.vector(mccf1_all),temp_lig,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_lig)),palette="dark3"))
temp_ythresh <- 0.25
text(temp_x[temp_y > temp_ythresh],temp_y[temp_y > temp_ythresh],
     labels=names(temp_y)[temp_y > temp_ythresh],pos=4,
     col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_y > temp_ythresh])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Average per cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(mccf1_new),temp_ct,mean) - 
  tapply(as.vector(mccf1_all),temp_ct,mean)
temp_y <- colMeans(rbind(tapply(as.vector(mccf1_new),temp_ct,mean),
                         tapply(as.vector(mccf1_all),temp_ct,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))
temp_ythresh <- 0.25
legend("topleft",bty="n",levels(temp_ct),pch=19,cex=0.9,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"),
       text.col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))

```

```{r lvl5_MA_MCC, echo=F,message=F,warning=F,fig.height=8,fig.width=9,fig.show='hold'}
temp_mcc_all <- sapply(names(scores_all),function(LIG) {
  sapply(names(scores_all[[LIG]]),function(CT) {
    mccr(as.integer(scores_all[[LIG]][[CT]]$label[!scores_all[[LIG]][[CT]]$train]),
         as.integer(scores_all[[LIG]][[CT]]$score[!scores_all[[LIG]][[CT]]$train] >= .5))
  })
})
temp_mcc_new <- sapply(names(scores_new),function(LIG) {
  sapply(names(scores_new[[LIG]]),function(CT) {
    mccr(as.integer(scores_new[[LIG]][[CT]]$label[!scores_new[[LIG]][[CT]]$train]),
         as.integer(scores_new[[LIG]][[CT]]$score[!scores_new[[LIG]][[CT]]$train] >= .5))
  })
})

temp_lig <- factor(sapply(colnames(temp_mcc_all),function(X) rep(X,nrow(temp_mcc_all))),levels=lig16)
temp_ct <- factor(sapply(colnames(temp_mcc_all),function(X) rownames(temp_mcc_all)),levels=ct14)

par(mfrow=c(2,2),mar=c(3,3,2,1),mgp=2:0)
plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Coloured by ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Coloured by cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Average per ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(temp_mcc_new),temp_lig,mean) - 
  tapply(as.vector(temp_mcc_all),temp_lig,mean)
temp_y <- colMeans(rbind(tapply(as.vector(temp_mcc_new),temp_lig,mean),
                         tapply(as.vector(temp_mcc_all),temp_lig,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_lig)),palette="dark3"))
temp_ythresh <- 0.1
text(temp_x[temp_y > temp_ythresh],temp_y[temp_y > temp_ythresh],
     labels=names(temp_y)[temp_y > temp_ythresh],pos=4,
     col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_y > temp_ythresh])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Average per cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(temp_mcc_new),temp_ct,mean) - 
  tapply(as.vector(temp_mcc_all),temp_ct,mean)
temp_y <- colMeans(rbind(tapply(as.vector(temp_mcc_new),temp_ct,mean),
                         tapply(as.vector(temp_mcc_all),temp_ct,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))
temp_ythresh <- 0.25
legend("topleft",bty="n",levels(temp_ct),pch=19,cex=0.9,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"),
       text.col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))

```

```{r lvl5_cleanup, echo=F,message=F,warning=F}
rm(list=c(temp_load1,temp_load2,grep("^temp",ls(),value=T)))
```

----

## All cell lines, level 4 data

```{r lvl4_load, echo=F,message=F,warning=F}
temp_load1 <- load("~/Dropbox/GDB_archive/CMapCorr_files/lvl4_inputs.RData")
temp_load2 <- load("~/Dropbox/GDB_archive/CMapCorr_files/200817_newVall_probs_lvl4.RData")

```


```{r lvl4_heatmap, echo=F,message=F,warning=F,fig.height=7,fig.width=9,fig.show='hold'}
temp_both <- do.call(rbind,lapply(rownames(mccf1_all),function(X) { 
  temp <- rbind(mccf1_new[X,],mccf1_all[X,]) 
  rownames(temp) <- c(X,paste0(X,"_ctrl"))
  return(temp)
}))

par(mar=c(1,5,7,1),mgp=2:0,las=2)
image(z=temp_both[,seq(ncol(temp_both),1)],
      x=1:nrow(temp_both),y=1:ncol(temp_both),
      col=sequential_hcl(100,palette="inferno",rev=T), #breaks=0:100,
      xaxt="n",yaxt="n",xlab=NA,ylab=NA)
mtext(rownames(temp_both),side=3,at=1:nrow(temp_both),adj=0,line=0.1)
mtext("Withheld cell line",side=3,line=5.5,cex=1.5,font=2,las=0)
mtext(rev(colnames(temp_both)),
      side=2,at=1:ncol(temp_both),adj=1,line=0.1)
mtext("Ligand",side=2,line=3.5,cex=1.5,font=2,las=0)
mtext("MCC/F1 metric %",side=1,line=0,at=nrow(temp_both) + 0.5,adj=1,las=0,col="dodgerblue")
text(as.vector(sapply(1:ncol(temp_both),function(X) 1:nrow(temp_both))),
     as.vector(sapply(ncol(temp_both):1,function(X) rep(X,nrow(temp_both)))),
     labels=as.vector(round(temp_both * 100)),cex=0.8,col="dodgerblue")

```

```{r lvl4_MA, echo=F,message=F,warning=F,fig.height=8,fig.width=9,fig.show='hold'}
temp_lig <- factor(sapply(colnames(mccf1_all),function(X) rep(X,nrow(mccf1_all))),levels=lig16)
temp_ct <- factor(sapply(colnames(mccf1_all),function(X) rownames(mccf1_all)),levels=ct14)

par(mfrow=c(2,2),mar=c(3,3,2,1),mgp=2:0)
plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Coloured by ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Coloured by cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Average per ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(mccf1_new),temp_lig,mean) - 
  tapply(as.vector(mccf1_all),temp_lig,mean)
temp_y <- colMeans(rbind(tapply(as.vector(mccf1_new),temp_lig,mean),
                         tapply(as.vector(mccf1_all),temp_lig,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_lig)),palette="dark3"))
temp_ythresh <- 0.25
text(temp_x[temp_y > temp_ythresh],temp_y[temp_y > temp_ythresh],
     labels=names(temp_y)[temp_y > temp_ythresh],pos=4,
     col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_y > temp_ythresh])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Average per cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(mccf1_new),temp_ct,mean) - 
  tapply(as.vector(mccf1_all),temp_ct,mean)
temp_y <- colMeans(rbind(tapply(as.vector(mccf1_new),temp_ct,mean),
                         tapply(as.vector(mccf1_all),temp_ct,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))
temp_ythresh <- 0.25
legend("topleft",bty="n",levels(temp_ct),pch=19,cex=0.9,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"),
       text.col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))

```

```{r lvl4_MA_MCC, echo=F,message=F,warning=F,fig.height=8,fig.width=9,fig.show='hold'}
temp_mcc_all <- sapply(names(scores_all),function(LIG) {
  sapply(names(scores_all[[LIG]]),function(CT) {
    mccr(as.integer(scores_all[[LIG]][[CT]]$label[!scores_all[[LIG]][[CT]]$train]),
         as.integer(scores_all[[LIG]][[CT]]$score[!scores_all[[LIG]][[CT]]$train] >= .5))
  })
})
temp_mcc_new <- sapply(names(scores_new),function(LIG) {
  sapply(names(scores_new[[LIG]]),function(CT) {
    mccr(as.integer(scores_new[[LIG]][[CT]]$label[!scores_new[[LIG]][[CT]]$train]),
         as.integer(scores_new[[LIG]][[CT]]$score[!scores_new[[LIG]][[CT]]$train] >= .5))
  })
})

temp_lig <- factor(sapply(colnames(temp_mcc_all),function(X) rep(X,nrow(temp_mcc_all))),levels=lig16)
temp_ct <- factor(sapply(colnames(temp_mcc_all),function(X) rownames(temp_mcc_all)),levels=ct14)

par(mfrow=c(2,2),mar=c(3,3,2,1),mgp=2:0)
plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Coloured by ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Coloured by cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Average per ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(temp_mcc_new),temp_lig,mean) - 
  tapply(as.vector(temp_mcc_all),temp_lig,mean)
temp_y <- colMeans(rbind(tapply(as.vector(temp_mcc_new),temp_lig,mean),
                         tapply(as.vector(temp_mcc_all),temp_lig,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_lig)),palette="dark3"))
temp_ythresh <- 0.1
text(temp_x[temp_y > temp_ythresh],temp_y[temp_y > temp_ythresh],
     labels=names(temp_y)[temp_y > temp_ythresh],pos=4,
     col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_y > temp_ythresh])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Average per cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(temp_mcc_new),temp_ct,mean) - 
  tapply(as.vector(temp_mcc_all),temp_ct,mean)
temp_y <- colMeans(rbind(tapply(as.vector(temp_mcc_new),temp_ct,mean),
                         tapply(as.vector(temp_mcc_all),temp_ct,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))
temp_ythresh <- 0.25
legend("topleft",bty="n",levels(temp_ct),pch=19,cex=0.9,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"),
       text.col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))

```

```{r lvl4_cleanup, echo=F,message=F,warning=F}
rm(list=c(temp_load1,temp_load2,grep("^temp",ls(),value=T)))
```

----

## All cell lines, level 3 data

```{r lvl3_load, echo=F,message=F,warning=F}
temp_load1 <- load("~/Dropbox/GDB_archive/CMapCorr_files/lvl3_inputs.RData")
temp_load2 <- load("~/Dropbox/GDB_archive/CMapCorr_files/200817_newVall_probs_lvl3.RData")

```


```{r lvl3_heatmap, echo=F,message=F,warning=F,fig.height=7,fig.width=9,fig.show='hold'}
temp_both <- do.call(rbind,lapply(rownames(mccf1_all),function(X) { 
  temp <- rbind(mccf1_new[X,],mccf1_all[X,]) 
  rownames(temp) <- c(X,paste0(X,"_ctrl"))
  return(temp)
}))

par(mar=c(1,5,7,1),mgp=2:0,las=2)
image(z=temp_both[,seq(ncol(temp_both),1)],
      x=1:nrow(temp_both),y=1:ncol(temp_both),
      col=sequential_hcl(100,palette="inferno",rev=T), #breaks=0:100,
      xaxt="n",yaxt="n",xlab=NA,ylab=NA)
mtext(rownames(temp_both),side=3,at=1:nrow(temp_both),adj=0,line=0.1)
mtext("Withheld cell line",side=3,line=5.5,cex=1.5,font=2,las=0)
mtext(rev(colnames(temp_both)),
      side=2,at=1:ncol(temp_both),adj=1,line=0.1)
mtext("Ligand",side=2,line=3.5,cex=1.5,font=2,las=0)
mtext("MCC/F1 metric %",side=1,line=0,at=nrow(temp_both) + 0.5,adj=1,las=0,col="dodgerblue")
text(as.vector(sapply(1:ncol(temp_both),function(X) 1:nrow(temp_both))),
     as.vector(sapply(ncol(temp_both):1,function(X) rep(X,nrow(temp_both)))),
     labels=as.vector(round(temp_both * 100)),cex=0.8,col="dodgerblue")

```

```{r lvl3_MA, echo=F,message=F,warning=F,fig.height=8,fig.width=9,fig.show='hold'}
temp_lig <- factor(sapply(colnames(mccf1_all),function(X) rep(X,nrow(mccf1_all))),levels=lig16)
temp_ct <- factor(sapply(colnames(mccf1_all),function(X) rownames(mccf1_all)),levels=ct14)

par(mfrow=c(2,2),mar=c(3,3,2,1),mgp=2:0)
plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Coloured by ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Coloured by cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Average per ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(mccf1_new),temp_lig,mean) - 
  tapply(as.vector(mccf1_all),temp_lig,mean)
temp_y <- colMeans(rbind(tapply(as.vector(mccf1_new),temp_lig,mean),
                         tapply(as.vector(mccf1_all),temp_lig,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_lig)),palette="dark3"))
temp_ythresh <- 0.25
text(temp_x[temp_y > temp_ythresh],temp_y[temp_y > temp_ythresh],
     labels=names(temp_y)[temp_y > temp_ythresh],pos=4,
     col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_y > temp_ythresh])

plot(as.vector(mccf1_new) - as.vector(mccf1_all),
     colMeans(rbind(as.vector(mccf1_new),as.vector(mccf1_all))),
     xlab="Withheld - Control MCC/F1 metric",ylab="Mean MCC/F1 metric",main="Average per cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(mccf1_new),temp_ct,mean) - 
  tapply(as.vector(mccf1_all),temp_ct,mean)
temp_y <- colMeans(rbind(tapply(as.vector(mccf1_new),temp_ct,mean),
                         tapply(as.vector(mccf1_all),temp_ct,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))
temp_ythresh <- 0.25
legend("topleft",bty="n",levels(temp_ct),pch=19,cex=0.9,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"),
       text.col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))

```

```{r lvl3_MA_MCC, echo=F,message=F,warning=F,fig.height=8,fig.width=9,fig.show='hold'}
temp_mcc_all <- sapply(names(scores_all),function(LIG) {
  sapply(names(scores_all[[LIG]]),function(CT) {
    mccr(as.integer(scores_all[[LIG]][[CT]]$label[!scores_all[[LIG]][[CT]]$train]),
         as.integer(scores_all[[LIG]][[CT]]$score[!scores_all[[LIG]][[CT]]$train] >= .5))
  })
})
temp_mcc_new <- sapply(names(scores_new),function(LIG) {
  sapply(names(scores_new[[LIG]]),function(CT) {
    mccr(as.integer(scores_new[[LIG]][[CT]]$label[!scores_new[[LIG]][[CT]]$train]),
         as.integer(scores_new[[LIG]][[CT]]$score[!scores_new[[LIG]][[CT]]$train] >= .5))
  })
})

temp_lig <- factor(sapply(colnames(temp_mcc_all),function(X) rep(X,nrow(temp_mcc_all))),levels=lig16)
temp_ct <- factor(sapply(colnames(temp_mcc_all),function(X) rownames(temp_mcc_all)),levels=ct14)

par(mfrow=c(2,2),mar=c(3,3,2,1),mgp=2:0)
plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Coloured by ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Coloured by cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Average per ligand",
     pch=20,col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_lig])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(temp_mcc_new),temp_lig,mean) - 
  tapply(as.vector(temp_mcc_all),temp_lig,mean)
temp_y <- colMeans(rbind(tapply(as.vector(temp_mcc_new),temp_lig,mean),
                         tapply(as.vector(temp_mcc_all),temp_lig,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_lig)),palette="dark3"))
temp_ythresh <- 0.1
text(temp_x[temp_y > temp_ythresh],temp_y[temp_y > temp_ythresh],
     labels=names(temp_y)[temp_y > temp_ythresh],pos=4,
     col=qualitative_hcl(length(levels(temp_lig)),palette="dark3")[temp_y > temp_ythresh])

plot(as.vector(temp_mcc_new) - as.vector(temp_mcc_all),
     colMeans(rbind(as.vector(temp_mcc_new),as.vector(temp_mcc_all))),
     xlab="Withheld - Control MCC @ 0.5",ylab="Mean MCC @ 0.5",main="Average per cell line",
     pch=20,col=qualitative_hcl(length(levels(temp_ct)),palette="dark3")[temp_ct])
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
     col=alpha("white",0.8))
abline(v=0,lty=2)
temp_x <- tapply(as.vector(temp_mcc_new),temp_ct,mean) - 
  tapply(as.vector(temp_mcc_all),temp_ct,mean)
temp_y <- colMeans(rbind(tapply(as.vector(temp_mcc_new),temp_ct,mean),
                         tapply(as.vector(temp_mcc_all),temp_ct,mean)))
points(temp_x,temp_y,pch=19,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))
temp_ythresh <- 0.25
legend("topleft",bty="n",levels(temp_ct),pch=19,cex=0.9,
       col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"),
       text.col=qualitative_hcl(length(levels(temp_ct)),palette="dark3"))

```

```{r lvl3_cleanup, echo=F,message=F,warning=F}
rm(list=c(temp_load1,temp_load2,grep("^temp",ls(),value=T)))
```

