---
title: "Extrapolating ligand prediction to left-out cell line"
---
  
```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
library(cmapR)
library(ranger)
library(colorspace)
library(kableExtra)
source("~/Dropbox/GDB/line2user.R")
knitr::opts_chunk$set(
  echo=F,
  message=F,
  warning=F
)
```

# Accuracy 

## Level 4

```{r load_data_lvl4}
if (exists("lvl4_data")) {
} else if (file.exists("~/Dropbox/GDB_archive/CMapCorr_files/lvl4_inputs.RData")) {
  load("~/Dropbox/GDB_archive/CMapCorr_files/lvl4_inputs.RData") 
} else {
  source("lvl4_inputs.R")
}
```

[Random forest model source code](https://github.com/BaderLab/Brendan_CCInxPred/blob/master/200708_lvl4_withhold1CT.R)  

```{r lvl4_RFwithholdCT,fig.height=4,fig.width=9,fig.show='hold'}
if (file.exists("~/Dropbox/GDB_archive/CMapCorr_files/200708_lvl4_withhold1CT.RData")) {
  temp <- load("~/Dropbox/GDB_archive/CMapCorr_files/200708_lvl4_withhold1CT.RData")
} else {
  source("200708_lvl4_withhold1CT.R")
}
lvl4_rfresults <- rfresults
lvl4_testIDs <- testIDs

rm(list=temp)
```


```{r lvl4_training_dist,eval=F}
t(sapply(ct14,function(CT) sapply(lig16,function(LIG) 
    sum(lvl4_data@cdesc[trainIDs[[1]],"cell_id"] == CT & lvl4_data@cdesc[trainIDs[[1]],"pert_iname"] == LIG))))



tempdf <- as.data.frame(
  sapply(trainIDs,function(X) table(factor(lvl4_data@cdesc[X,"cell_id"],levels=ct14)))
)

kable(tempdf,format="html")  %>%
  kable_styling()

```

```{r lvl4_confusion_matrix_calc, echo=F,message=F,warning=F}
confusionCT <- sapply(ct14,function(CT) {
  temp_confusion <- table(true=factor(lvl4_data@cdesc[lvl4_testIDs[[CT]],"pert_iname"],levels=lig16),
                          predicted=lvl4_rfresults[[CT]]$predictions)
  return(sweep(temp_confusion,1,rowSums(temp_confusion),"/"))
},simplify=F)

lvl4_acc_ct <- t(sapply(confusionCT,diag))
lvl4_counts <- t(sapply(ct14,function(CT) 
  table(factor(lvl4_data@cdesc[lvl4_testIDs[[CT]],"pert_iname"],levels=lig16))))
```

```{r lvl4_confusion_matrix_perCT_plot, eval=F,echo=F,message=F,warning=F,fig.height=7,fig.width=7,fig.show='hold'}
for (CT in ct14) {
  par(mar=c(1,5,5,1),mgp=2:0,las=2)
  image(z=t(confusionCT[[CT]] * 100)[,seq(nrow(confusionCT[[CT]]),1)],
        x=1:nrow(confusionCT[[CT]]),y=1:ncol(confusionCT[[CT]]),
        col=sequential_hcl(100,palette="inferno",rev=T),breaks=0:100,
        xaxt="n",yaxt="n",xlab=NA,ylab=NA)
  mtext(rev(colnames(confusionCT[[CT]])),side=2,at=1:nrow(confusionCT[[CT]]),adj=1.1)
  mtext("Truth",side=2,line=3.5,at=((nrow(confusionCT[[CT]])-1)/2)+1,las=0,font=2,cex=1.5)
  mtext(rownames(confusionCT[[CT]]),side=3,at=1:nrow(confusionCT[[CT]]),adj=-0.1)
  mtext("Prediction",side=3,line=3.5,at=((nrow(confusionCT[[CT]])-1)/2)+1,las=0,font=2,cex=1.5)
  text(x=seq(1,nrow(confusionCT[[CT]])),y=seq(nrow(confusionCT[[CT]]),1),
       labels=round(diag(confusionCT[[CT]]),2),font=2,col="dodgerblue")
}
```



```{r lvl4_accuracy_heatmap, echo=F,message=F,warning=F,fig.height=5,fig.width=7,fig.show='hold'}
par(mar=c(2,13,5,1),mgp=2:0,las=2)
image(z=t(lvl4_acc_ct * 100)[,seq(nrow(lvl4_acc_ct),1)],
      x=1:ncol(lvl4_acc_ct),y=1:nrow(lvl4_acc_ct),
      col=sequential_hcl(100,palette="inferno",rev=T),breaks=0:100,
      xaxt="n",yaxt="n",xlab=NA,ylab=NA)
mtext(colnames(lvl4_acc_ct),side=3,at=1:ncol(lvl4_acc_ct),adj=0,line=0.1)
mtext("Ligands",side=3,line=3.5,at=((ncol(lvl4_acc_ct)-1)/2)+1,las=0,font=2,cex=1.5)
mtext(rev(rownames(lvl4_acc_ct)),
      side=2,at=1:nrow(lvl4_acc_ct),adj=1,line=0.1)
mtext("Cell Types",side=3,line=0.1,at=0.2,adj=1,las=0,font=2,cex=1.5)
text(as.vector(sapply(1:ncol(lvl4_counts),function(X) rep(X,nrow(lvl4_counts)))),
     as.vector(sapply(1:ncol(lvl4_counts),function(X) nrow(lvl4_counts):1)),
     labels=as.vector(lvl4_counts),cex=0.8,col="dodgerblue")
mtext(paste("Sample","number",sep="\n"),
      side=1,line=1,at=ncol(lvl4_acc_ct) + 0.5,adj=1,las=0,col="dodgerblue")
segments(x0=seq(2.5,11.5,length.out=1000),
         x1=seq(2.5,11.5,length.out=1000),
         y0=rep(-0.1,1000),y1=rep(0.3,1000),
         xpd=NA,col=sequential_hcl(1000,palette="inferno",rev=T))
mtext(c("0%","100%"),las=0,side=1,at=c(2.5,11.5),adj=c(1.1,-0.1))
mtext("Accuracy",las=0,side=1,line=0.9,at=7,adj=0.5)

```


## Level 5


```{r load_data_lvl5}
if (exists("lvl5_data")) {
} else if (file.exists("~/Dropbox/GDB_archive/CMapCorr_files/lvl5_inputs.RData")) {
  load("~/Dropbox/GDB_archive/CMapCorr_files/lvl5_inputs.RData") 
} else {
  source("lvl5_inputs.R")
}
```

[Random forest model source code](https://github.com/BaderLab/Brendan_CCInxPred/blob/master/200708_lvl5_withhold1CT.R)  

```{r lv5_RFwithholdCT,fig.height=4,fig.width=9,fig.show='hold'}
if (file.exists("~/Dropbox/GDB_archive/CMapCorr_files/200708_lvl5_withhold1CT.RData")) {
  temp <- load("~/Dropbox/GDB_archive/CMapCorr_files/200708_lvl5_withhold1CT.RData")
} else {
  source("200708_lvl5_withhold1CT.R")
}
lvl5_rfresults <- rfresults
lvl5_testIDs <- testIDs

rm(list=temp)
```


```{r lv5_training_dist,eval=F}
t(sapply(ct14,function(CT) sapply(lig16,function(LIG) 
    sum(lvl5_data@cdesc[trainIDs[[1]],"cell_id"] == CT & lvl5_data@cdesc[trainIDs[[1]],"pert_iname"] == LIG))))



tempdf <- as.data.frame(
  sapply(trainIDs,function(X) table(factor(lvl5_data@cdesc[X,"cell_id"],levels=ct14)))
)

kable(tempdf,format="html")  %>%
  kable_styling()

```

```{r lv5_confusion_matrix_calc, echo=F,message=F,warning=F}
confusionCT <- sapply(ct14,function(CT) {
  temp_confusion <- table(true=factor(lvl5_data@cdesc[lvl5_testIDs[[CT]],"pert_iname"],levels=lig16),
                          predicted=lvl5_rfresults[[CT]]$predictions)
  return(sweep(temp_confusion,1,rowSums(temp_confusion),"/"))
},simplify=F)

lvl5_acc_ct <- t(sapply(confusionCT,diag))
lvl5_counts <- t(sapply(ct14,function(CT) 
  table(factor(lvl5_data@cdesc[lvl5_testIDs[[CT]],"pert_iname"],levels=lig16))))

rm(list=temp)
```

```{r lv5_confusion_matrix_perCT_plot, eval=F,echo=F,message=F,warning=F,fig.height=7,fig.width=7,fig.show='hold'}
for (CT in ct14) {
  par(mar=c(1,5,5,1),mgp=2:0,las=2)
  image(z=t(confusionCT[[CT]] * 100)[,seq(nrow(confusionCT[[CT]]),1)],
        x=1:nrow(confusionCT[[CT]]),y=1:ncol(confusionCT[[CT]]),
        col=sequential_hcl(100,palette="inferno",rev=T),breaks=0:100,
        xaxt="n",yaxt="n",xlab=NA,ylab=NA)
  mtext(rev(colnames(confusionCT[[CT]])),side=2,at=1:nrow(confusionCT[[CT]]),adj=1.1)
  mtext("Truth",side=2,line=3.5,at=((nrow(confusionCT[[CT]])-1)/2)+1,las=0,font=2,cex=1.5)
  mtext(rownames(confusionCT[[CT]]),side=3,at=1:nrow(confusionCT[[CT]]),adj=-0.1)
  mtext("Prediction",side=3,line=3.5,at=((nrow(confusionCT[[CT]])-1)/2)+1,las=0,font=2,cex=1.5)
  text(x=seq(1,nrow(confusionCT[[CT]])),y=seq(nrow(confusionCT[[CT]]),1),
       labels=round(diag(confusionCT[[CT]]),2),font=2,col="dodgerblue")
}
```



```{r lv5_accuracy_heatmap, echo=F,message=F,warning=F,fig.height=5,fig.width=7,fig.show='hold'}
par(mar=c(2,13,5,1),mgp=2:0,las=2)
image(z=t(lvl5_acc_ct * 100)[,seq(nrow(lvl5_acc_ct),1)],
      x=1:ncol(lvl5_acc_ct),y=1:nrow(lvl5_acc_ct),
      col=sequential_hcl(100,palette="inferno",rev=T),breaks=0:100,
      xaxt="n",yaxt="n",xlab=NA,ylab=NA)
mtext(colnames(lvl5_acc_ct),side=3,at=1:ncol(lvl5_acc_ct),adj=0,line=0.1)
mtext("Ligands",side=3,line=3.5,at=((ncol(lvl5_acc_ct)-1)/2)+1,las=0,font=2,cex=1.5)
mtext(rev(rownames(lvl5_acc_ct)),
      side=2,at=1:nrow(lvl5_acc_ct),adj=1,line=0.1)
mtext("Cell Types",side=3,line=0.1,at=0.2,adj=1,las=0,font=2,cex=1.5)
text(as.vector(sapply(1:ncol(lvl5_counts),function(X) rep(X,nrow(lvl5_counts)))),
     as.vector(sapply(1:ncol(lvl5_counts),function(X) nrow(lvl5_counts):1)),
     labels=as.vector(lvl5_counts),cex=0.8,col="dodgerblue")
mtext(paste("Sample","number",sep="\n"),
      side=1,line=1,at=ncol(lvl4_acc_ct) + 0.5,adj=1,las=0,col="dodgerblue")
segments(x0=seq(2.5,11.5,length.out=1000),
         x1=seq(2.5,11.5,length.out=1000),
         y0=rep(-0.1,1000),y1=rep(0.3,1000),
         xpd=NA,col=sequential_hcl(1000,palette="inferno",rev=T))
mtext(c("0%","100%"),las=0,side=1,at=c(2.5,11.5),adj=c(1.1,-0.1))
mtext("Accuracy",las=0,side=1,line=0.9,at=7,adj=0.5)
```


## Compared to Level 5 control assay (leave-one-out)


```{r RF_leave1out}
if (file.exists("~/Dropbox/GDB_archive/CMapCorr_files/200524_lvl5_mixall_balanced_leave1out_results.RData")) {
  temp <- load("~/Dropbox/GDB_archive/CMapCorr_files/200524_lvl5_mixall_balanced_leave1out_results.RData")
} else {
  source("200524_lvl5_mixall_leave1out.R")
}

lvl5L1O_testresults <- data.frame(
  IDs=as.vector(testIDs),
  Labels=as.vector(t(sapply(rfresults,function(X) X$predictions))),
  stringsAsFactors=F
)
test_hits <- vector("list",sum(lvl5_data@cdesc$pert_iname %in% lig16))
names(test_hits) <- rownames(lvl5_data@cdesc)[lvl5_data@cdesc$pert_iname %in% lig16]

for (X in 1:nrow(lvl5L1O_testresults)) {
  test_hits[[lvl5L1O_testresults[X,"IDs"]]] <- append(test_hits[[lvl5L1O_testresults[X,"IDs"]]],
                                               lvl5L1O_testresults[X,"Labels"])
}

acc_leave1out <- sapply(names(test_hits),function(X) 
  sum(test_hits[[X]] == lvl5_data@cdesc[X,"pert_iname"]) / 
    length(test_hits[[X]]))
acc_leave1out_totals <- sapply(lig16,function(X) {
  Y <- rownames(lvl5_data@cdesc)[lvl5_data@cdesc$pert_iname == X]
  return(sum(unlist(test_hits[Y]) == X) / 
           length(unlist(test_hits[Y])))
})

acc_leave1out_ct <- sapply(lig16,function(X) {
  sapply(ct14,function(Y) {
    Z <- rownames(lvl5_data@cdesc)[lvl5_data@cdesc$pert_iname == X &
                                     lvl5_data@cdesc$cell_id == Y]
    return(sum(unlist(test_hits[Z]) == X) / 
             length(unlist(test_hits[Z])))
  })
})

test_counts <- sapply(lig16,function(X) {
  sapply(ct14,function(Y) {
    sum(lvl5_data@cdesc$pert_iname == X &
          lvl5_data@cdesc$cell_id == Y)
  })
})

test_predictions <- sapply(lig16,function(X) {
  sapply(ct14,function(Y) {
    temp <- rownames(lvl5_data@cdesc)[lvl5_data@cdesc$pert_iname == X &
                                        lvl5_data@cdesc$cell_id == Y]
    return(table(factor(unlist(test_hits[temp]),levels=lig16)) / 
             length(unlist(test_hits[temp])))
  })
},simplify=F)

rm(X)
```

```{r leave1out_acc_ct,fig.height=5,fig.width=7,fig.show='hold'}
# see {RF_leave1out} for input code for this figure.

par(mar=c(2,13,5,1),mgp=2:0,las=2)
image(z=t(acc_leave1out_ct * 100)[,seq(nrow(acc_leave1out_ct),1)],
      x=1:ncol(acc_leave1out_ct),y=1:nrow(acc_leave1out_ct),
      col=sequential_hcl(100,palette="inferno",rev=T),breaks=0:100,
      xaxt="n",yaxt="n",xlab=NA,ylab=NA)
mtext(colnames(acc_leave1out_ct),side=3,at=1:ncol(acc_leave1out_ct),adj=0,line=0.1)
mtext("Ligands",side=3,line=3.5,at=((ncol(acc_leave1out_ct)-1)/2)+1,las=0,font=2,cex=1.5)
mtext(rev(rownames(acc_leave1out_ct)),
      side=2,at=1:nrow(acc_leave1out_ct),adj=1,line=0.1)
mtext("Cell Types",side=3,line=0.1,at=0.2,adj=1,las=0,font=2,cex=1.5)
text(as.vector(sapply(1:ncol(test_counts),function(X) rep(X,nrow(test_counts)))),
     as.vector(sapply(1:ncol(test_counts),function(X) nrow(test_counts):1)),
     labels=as.vector(test_counts),cex=0.8,col="dodgerblue")
mtext(paste("Sample","number",sep="\n"),
      side=1,line=1,at=ncol(lvl4_acc_ct) + 0.5,adj=1,las=0,col="dodgerblue")
segments(x0=seq(2.5,11.5,length.out=1000),
         x1=seq(2.5,11.5,length.out=1000),
         y0=rep(-0.1,1000),y1=rep(0.3,1000),
         xpd=NA,col=sequential_hcl(1000,palette="inferno",rev=T))
mtext(c("0%","100%"),las=0,side=1,at=c(2.5,11.5),adj=c(1.1,-0.1))
mtext("Accuracy",las=0,side=1,line=0.9,at=7,adj=0.5)
```


```{r lvl4_vs_l1o,fig.height=8,fig.width=8,fig.show='hold'}
temp_ct <- as.vector(sapply(qualitative_hcl(length(ct14),palette="dark3"),rep,2))
temp_lig <- qualitative_hcl(length(lig16),palette="dark3")[as.vector(sapply(1:8,function(X) c(X,X + 8)))]
names(temp_lig) <- colnames(acc_leave1out_ct)

temp_both <- do.call(cbind,lapply(rownames(acc_leave1out_ct),function(X) { 
  temp <- cbind(acc_leave1out_ct[X,],lvl4_acc_ct[X,])
  colnames(temp) <- c(paste0("CTRL_",X),X)
  return(temp)
}))

par(mar=c(2,14,5,1),mgp=2:0,las=2)
image(z=temp_both[,seq(ncol(temp_both),1)],
      x=1:nrow(temp_both),y=1:ncol(temp_both),
      col=sequential_hcl(100,palette="Inferno",rev=T),
      breaks=seq(0,1,length.out=101),
      xaxt="n",yaxt="n",xlab=NA,ylab=NA)
abline(h=seq(2.5,ncol(temp_both) - 1.5,2),col="white")

mtext(rownames(temp_both),side=3,at=1:nrow(temp_both),adj=0,line=0.1,col=temp_lig)
mtext("Withheld cell line",side=3,line=0.1,at=0.3,adj=1,las=0,font=2,cex=1.5)

mtext(rev(colnames(temp_both)),col=rev(temp_ct),
      side=2,at=1:ncol(temp_both),adj=1,line=0.1)
mtext("Ligand",side=3,line=3.5,cex=1.5,font=2,las=0)

text(as.vector(sapply(1:ncol(temp_both),function(X) 1:nrow(temp_both))),
     as.vector(sapply(ncol(temp_both):1,function(X) rep(X,nrow(temp_both)))),
     labels=as.vector(round(temp_both * 100)),cex=0.8,col="dodgerblue")
mtext("% Accuracy",side=1,line=0.1,at=nrow(temp_both) + 0.5,adj=1,las=0,col="dodgerblue")

segments(x0=seq(2,9,length.out=1000),
         x1=seq(2,9,length.out=1000),
         y0=rep(-0.1,1000),y1=rep(0.3,1000),
         xpd=NA,col=sequential_hcl(1000,palette="inferno",rev=T))
mtext(c("0%","100%"),las=0,side=1,at=c(2,9),adj=c(1.1,-0.1))
mtext("Accuracy",las=0,side=1,line=0.9,at=5.5,adj=0.5)

mtext("A",side=3,at=line2user(13,2),line=3.5,font=2,cex=1.5,las=0)
```

```{r ALL_lvl4_volcplot, echo=F,message=F,warning=F,fig.height=4,fig.width=8,fig.show='hold'}
temp_x <- lvl4_acc_ct - acc_leave1out_ct
temp_y <- (lvl4_acc_ct + acc_leave1out_ct) / 2
temp_x2 <- apply(temp_x,2,median)
temp_y2 <- apply(temp_y,2,median)
temp_stat <- apply(temp_x,2,function(X) wilcox.test(X)$p.value)
par(mar=c(3,3,1,10),mgp=2:0)
plot(NA,NA,xlim=range(temp_x),ylim=range(-log10(temp_stat)),yaxt="n",
     xlab="Withheld - control accuracy",ylab="Wilcoxon signed-rank test p-value")
axis(2,at=-log10(c(1,0.1,0.05,0.01,1e-3,1e-4)),
     labels=c(1,0.1,0.05,0.01,1e-3,1e-4))
abline(v=0,lty=2)
temp <- sapply(colnames(temp_x),function(X) 
  lines(range(temp_x[,X]),rep(-log10(temp_stat[X]),2),col=temp_lig[X]))
points(temp_x2,-log10(temp_stat),pch=19,col=temp_lig)
legend(x=line2user(0,4),
       y=par("usr")[3] + (par("usr")[4] - par("usr")[3]) / 2,
       yjust=0.5,bty="n",xpd=NA,pch=19,col=temp_lig[order(temp_stat)],cex=0.98,
       legend=paste0(names(temp_lig)[order(temp_stat)],
         " (",round(colMeans(acc_leave1out_ct) * 100)[order(temp_stat)],"%)"))
mtext("Ligand (Mean ctrl Acc%)",side=3,line=-0.1,at=line2user(0.1,4),adj=0)

mtext("B",side=3,at=line2user(2,2),line=-0.5,font=2,cex=1.5,las=0)
```
```{r diff_stat, echo=F}
temp <- wilcox.test(as.vector(lvl4_acc_ct),as.vector(acc_leave1out_ct),paired=T,conf.int=T)
temp

print(paste0("Mean accuracy of control: ",round(mean(acc_leave1out_ct) * 100),"%"))
print(paste0("Mean accuracy of withheld: ",round(mean(lvl4_acc_ct) * 100),"%"))

print(paste0("Median pairwise change in accuracy in withheld cell lines relative to control was ",
             round(temp$estimate * 100),"% (p = ",
             signif(temp$p.value,2)," by Wilcoxon signed-rank test)."))
```


```{r vs_lvl5_leave1out_new, echo=FALSE,message=FALSE,warning=FALSE,fig.height=4,fig.width=7}
temp_acc <- data.frame(lvl5L1O=as.vector(acc_leave1out_ct),
                       lvl5CT=as.vector(lvl5_acc_ct),
                       lvl4CT=as.vector(lvl4_acc_ct))
temp_col <- qualitative_hcl(nrow(temp_acc),palette="dynamic",alpha=0.5)


par(mfrow=c(1,2),mar=c(3,3,1,1),mgp=2:0)
plot(NA,NA,xlim=c(0.9,3.1),ylim=c(0,1),
     ylab="Accuracy",xaxt="n",xlab=NA)
for (X in 1:nrow(temp_acc)) {
  points(jitter(1:3,amount=0.1),temp_acc[X,],type="b",pch=20,col=temp_col[X])
}
boxplot(temp_acc)

wilcox.test(temp_acc$lvl5L1O,temp_acc$lvl4CT,paired=T)
```


```{r vs_lvl5_leave1out, echo=FALSE,message=FALSE,warning=FALSE,fig.height=4,fig.width=7,fig.show='hold'}
temp <- list(lvl5_l1o=as.vector(acc_leave1out_ct),
             lvl5_ct=as.vector(lvl5_acc_ct),
             lvl4_ct=as.vector(lvl4_acc_ct))
par(mar=c(3,3,1,5),mgp=2:0,las=1)
boxplot(list(lvl4=temp$lvl4_ct - temp$lvl5_l1o,
             lvl5=temp$lvl5_ct - temp$lvl5_l1o),
        ylim=c(-1,1),pch=".",cex=2,horizontal=T,
        xlab="Difference in accuracy compared to lvl5_leave1out")
abline(v=0,lty=2)
tempW <- wilcox.test(temp$lvl4_ct - temp$lvl5_l1o,conf.int=T)
mtext(paste("Median ~",
            round(tempW$conf.int[2],3),
            round(tempW$conf.int[1],3),
            paste("p =",signif(tempW$p.value,2)),
            sep="\n"),
      side=4,at=1,line=0.5)
tempW <- wilcox.test(temp$lvl5_ct - temp$lvl5_l1o,conf.int=T)
mtext(paste("Median ~",
            round(tempW$conf.int[2],3),
            round(tempW$conf.int[1],3),
            paste("p =",signif(tempW$p.value,2)),
            sep="\n"),
      side=4,at=2,line=0.5)

```


****

# MCC

Redone with multiclass MCC score (from Yardstick package) instead of accuracy.

```{r}
rm(list=ls()[!ls() %in% c("lvl4_data","lvl4_rfresults","lvl4_testIDs",
                          "lvl5_data","lvl5_rfresults","lvl4_testIDs",
                          "lvl5L1O_testresults","ct14","lig16")])
```

```{r CTRL_confusion}
lvl5L1O_testresults$Labels <- as.factor(lvl5L1O_testresults$Labels)
lvl5L1O_testresults$Truth <- as.factor(lvl5_data@cdesc[lvl5L1O_testresults$IDs,"pert_iname"])
lvl5L1O_testresults$CellType <- as.factor(lvl5_data@cdesc[lvl5L1O_testresults$IDs,"cell_id"])

print(paste("Lvl5 leave one out (CTRL) MCC:",
            yardstick::mcc_vec(lvl5L1O_testresults$Truth,
                               lvl5L1O_testresults$Labels)))
  
```


```{r lvl4_confusion,eval=F}
CT <- "VCAP"
table(true=factor(lvl4_data@cdesc[lvl4_testIDs[[CT]],"pert_iname"],levels=lig16),
                          predicted=lvl4_rfresults[[CT]]$predictions)
```




