---
title: "Re-analysis of NicheNet dataset"
---
  
```{r setup, include=F}
library(colorspace)
library(scales)
source("~/Dropbox/GDB/line2user.R")
knitr::opts_chunk$set(
  echo=F,
  message=F,
  warning=F
)
```

# Figure 5a

```{r AvC_load_data}
load("~/Dropbox/GDB_archive/CMapCorr_files/NN_ALLvCT_dat.RData")
load("~/Dropbox/GDB_archive/CMapCorr_files/NN_ALLvCT_corr.RData")
source("~/Dropbox/GDB/line2user.R")
```

```{r AvC_corr_plot,fig.height=4,fig.width=8}
temp_order <- names(sort(sapply(unique(c(names(corr_all),names(corr_ct))),
                                function(X) mean(c(corr_all[[X]],corr_ct[[X]])))))
lig_col <- qualitative_hcl(length(nn_ligands),palette="dark3",alpha=0.5)
temp_colnames <- c(temp_order,nn_ligands[!nn_ligands %in% temp_order])
names(lig_col) <- temp_colnames[unlist(sapply(seq(1,ceiling(length(nn_ligands)/2)),
                                              function(X) c(X,X + ceiling(length(nn_ligands)/2)),
                                              simplify=F))]
temp_corr <- list(ALL=corr_all[temp_order[temp_order %in% names(corr_all)]],
               CT=corr_ct[temp_order[temp_order %in% names(corr_ct)]])
temp_lig <- sapply(strsplit(names(unlist(temp_corr,recursive=F)),".",fixed=T),"[[",2)


layout(rbind(1:2),widths=c(4,1))

par(mar=c(5,4,1,0.5),mgp=2:0)
plot(NA,NA,xlim=c(1,length(unlist(temp_corr,recursive=F))),ylim=range(temp_corr),
     xaxt="n",xlab=NA,ylab="Spearman correlation of log(fold-change)")
abline(v=sapply(temp_corr,length)[1] + 0.5,col="grey70")
abline(h=0,lty=2,col="grey50")
temp_x <- unlist(mapply(rep,x=seq_along(unlist(temp_corr,recursive=F)),
                        times=sapply(unlist(temp_corr,recursive=F),length)))
points(x=jitter(temp_x,amount=0.2),y=unlist(temp_corr),
       pch=19,col=lig_col[temp_lig][temp_x])
mtext(temp_lig,side=1,line=0.1,at=seq_along(temp_lig),las=3,col=alpha(lig_col[temp_lig],1))

segments(x0=c(0,sapply(temp_corr,length)[1]) + 0.75,
         x1=cumsum(sapply(temp_corr,length)) + 0.25,
         y0=line2user(4,1),y1=line2user(4,1),xpd=NA,lwd=2)
segments(x0=c(c(0,sapply(temp_corr,length)[1]) + 0.75,
              cumsum(sapply(temp_corr,length)) + 0.25),
         x1=c(c(0,sapply(temp_corr,length)[1]) + 0.75,
              cumsum(sapply(temp_corr,length)) + 0.25),
         y0=line2user(4,1),y1=line2user(3.8,1),xpd=NA,lwd=2)
mtext(c("Pairwise across all cell types","Pairwise within same cell type"),
      at=0.5 + cumsum(sapply(temp_corr,length)) - sapply(temp_corr,length) / 2,
      side=1,line=4)
mtext("A",font=2,cex=1.5,line=-0.5,side=3,las=0,at=line2user(3.5,2))


par(mar=c(5,0,1,3))
boxplot(list(ALL=unlist(corr_all),CT=unlist(corr_ct)),
        xaxt="n",xlab=NA,yaxt="n",ylab=NA)
axis(4)
mtext("Spearman correlation of log(fold-change)",side=4,line=2)
mtext(c("Across all","Cell type"),side=1,line=0.1,at=1:2,las=3)

mtext(paste0("p=",signif(wilcox.test(unlist(corr_all),unlist(corr_ct))$p.value,2)),
      side=1,line=-0.1,at=1.5,las=3,adj=0,cex=0.7)

rm(list=grep("^temp",ls(),value=T))
```

```{r echo=TRUE}
mean(unlist(corr_all))
median(unlist(corr_all))
mean(unlist(corr_ct))
median(unlist(corr_ct))
```


# Figure 5b  

```{r AvC_diffexp_boxplot_v3, fig.height=4,fig.width=8}
charLFC <- "4"; charFDR <- "01"
load(paste0("~/Dropbox/GDB_archive/CMapCorr_files/NN_ALLvCT_DEovlp_",
            "LFC",charLFC,"FDR",charFDR,".RData"))
temp_y <- lapply(c(ALL="P_all",CT="P_ct"),function(X) -log10(unlist(get(X))))
temp_x <- list(ALL=sapply(de_all,length),
               CT=sapply(unlist(de_ct,F,T),length))
temp_CTnames <- names(temp_y$CT)
names(temp_y$CT) <- sapply(strsplit(temp_CTnames,".",fixed=T),"[[",1)
names(temp_y$CT)[names(temp_y$CT) %in% unique(names(temp_y$CT)[duplicated(names(temp_y$CT))])] <- 
  temp_CTnames[names(temp_y$CT) %in% unique(names(temp_y$CT)[duplicated(names(temp_y$CT))])]
names(temp_x$CT) <- names(temp_y$CT)

Plist <- Pstat <- list()
for (charLFC in c("2","4")) {
  for (charFDR in c("1","01")) {
    temp_ds <- load(paste0("~/Dropbox/GDB_archive/CMapCorr_files/NN_ALLvCT_DEovlp_",
                        "LFC",charLFC,"FDR",charFDR,".RData"))
    Plist[[length(Plist) + 1]] <- lapply(c(ALL="P_all",CT="P_ct"),function(X) -log10(unlist(get(X))))
    Pstat[[length(Pstat) + 1]] <- wilcox.test(unlist(P_all),unlist(P_ct))$p.value
    names(Plist)[length(Plist)] <- paste("|Log2FC| \u2265",
                                         log2(as.integer(charLFC)),
                                         "& FDR \u2264",
                                         as.numeric(paste0("0.",charFDR)))
    rm(list=temp_ds)
  }
}


par(mfrow=c(1,2),mar=c(5,4,1,0.2),mgp=2:0)
plot(NA,NA,xlim=range(unlist(temp_x)),ylim=range(unlist(Plist)),
     yaxt="n",ylab="P # DE shared by chance",xlab=NA)
axis(2,at=-log10(c(1,0.1,0.05,1e-2,1e-3,1e-4,1e-5)),
     labels=c("100%","10%","5%","1%","0.1%","0.01%","0.001%"))
points(jitter(temp_x$ALL,2),jitter(temp_y$ALL,2),pch=20,col=alpha("red",0.5))
points(jitter(temp_x$CT,2),jitter(temp_y$CT,2),pch=20,col=alpha("dodgerblue",0.5))
text(temp_x$ALL[temp_y$ALL > -log10(0.05)],temp_y$ALL[temp_y$ALL > -log10(0.05)],
     names(temp_y$ALL)[temp_y$ALL > -log10(0.05)],col="red",cex=0.6,pos=3,offset=0.2)
temp_lab1 <- data.frame(x=temp_x$CT[temp_y$CT > -log10(0.05)],
                        y=temp_y$CT[temp_y$CT > -log10(0.05)])
temp_lab2 <- temp_lab1["TGFB1.fibroblast",,drop=F]
temp_lab1 <- temp_lab1[rownames(temp_lab1) != "TGFB1.fibroblast",]
text(temp_lab1,labels=rownames(temp_lab1),
     col="dodgerblue",cex=0.6,offset=0.2,
     pos=c(4,2)[(rownames(temp_lab1) == "BDNF") + 1])
text(temp_lab2,labels=rownames(temp_lab2),
     col="dodgerblue",cex=0.6,offset=0.2,adj=c(-0.01,-0.2))
legend("topright",bty="n",pch=20,col=alpha(c("red","dodgerblue"),0.5),
       legend=c("Across cell types","Within cell type"),cex=0.9,pt.cex=1,x.intersp=0.8)
mtext(paste("# DE shared at",
                paste("|Log2FC| \u2265",
                      log2(as.integer(charLFC)),
                      "& FDR \u2264",
                      as.numeric(paste0("0.",charFDR))),
                sep="\n"),
      side=1,line=3)

mtext("B",font=2,cex=1.5,line=-0.5,side=3,las=0,at=line2user(3.5,2))

par(mar=c(5,0,1,3))
boxplot(unlist(Plist,F,F),pch=20,yaxt="n",xaxt="n",ylab=NA,
        at=seq(1,12)[-seq(3,by=3,length.out=4)],
        col=alpha(c("red","dodgerblue"),0.5),
        border=c("red","dodgerblue"))
axis(4,at=-log10(c(1,0.1,0.05,1e-2,1e-3,1e-4,1e-5)),
     labels=c("100%","10%","5%","1%","0.1%","0.01%","0.001%"))
mtext("P # DE shared by chance",side=4,line=2)
axis(1,at=seq(1.5,by=3,length.out=4),labels=F)
text(seq(1.5,by=3,length.out=4),line2user(1,1),
     sub("&","\n&",names(Plist)),xpd=NA,adj=0,srt=315,cex=0.9)
mtext(paste("p =",signif(unlist(Pstat),2)),side=3,line=0,
      at=seq(1.5,by=3,length.out=4),cex=0.9)

```

****

